/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import bd.Conexion;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author alumnat
 */
public class CreditPage extends javax.swing.JFrame {

    private final int idUser;
    private Conexion conexion;
    int saldo;
    int creditos_actuales;
    String textoDelJTextField;

    /**
     * Creates new form MainPage
     */
    public CreditPage(int idUser) {
        initComponents();
        this.setLocationRelativeTo(null); //Inicializa al centro de la pantalla

        ImageIcon icon = new ImageIcon(getClass().getResource("/imagenes/Logo_Book4u.png")); // Esto es para cambiar el icono de la app
        Image image = icon.getImage();
        setIconImage(image);
        this.idUser = idUser;

        String nombreUsuario = getNombreUsuarioPorId(idUser);
        creditos_actuales = getCreditosPorId(idUser);
        jLabel20.setText(nombreUsuario);
        jLabel2.setText(String.valueOf(creditos_actuales));
    }

    private CreditPage() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    // Método para validar las credenciales en la base de datos
    private String getNombreUsuarioPorId(int id) {
        Conexion conexion = new Conexion();
        Connection connection = conexion.DatabaseConnection(); // Obtén la conexión
        String nombre = "";

        try {
            // Consulta SQL para verificar las credenciales
            String consulta = "SELECT * FROM usuarios WHERE id = ?";
            PreparedStatement statement = connection.prepareStatement(consulta);
            statement.setInt(1, id);

            ResultSet resultado = statement.executeQuery();
            // Si se encontraron resultados, las credenciales son válidas
            if (resultado.next()) {
                nombre = resultado.getString("Nombre");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return nombre;
    }

    private int getCreditosPorId(int id) {
        Conexion conexion = new Conexion();
        Connection connection = conexion.DatabaseConnection(); // Obtén la conexión
        int creditos = 0;

        try {
            // Consulta SQL para obtener los créditos del usuario por su ID
            String consulta = "SELECT credito FROM usuarios WHERE id = ?";
            PreparedStatement statement = connection.prepareStatement(consulta);
            statement.setInt(1, id);

            ResultSet resultado = statement.executeQuery();
            // Si se encontraron resultados, obtenemos los créditos del usuario
            if (resultado.next()) {
                creditos = resultado.getInt("credito");
            }
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            // Recuerda cerrar la conexión y otros recursos relacionados con la base de datos
            try {
                connection.close();
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
        return creditos;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        inputDinero = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btn50euros = new javax.swing.JButton();
        btn80euros = new javax.swing.JButton();
        btn40euros = new javax.swing.JButton();
        btn10euros = new javax.swing.JButton();
        btn20euros = new javax.swing.JButton();
        btn30euros = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(255, 222, 89));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inputDinero.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        inputDinero.setForeground(new java.awt.Color(153, 153, 153));
        inputDinero.setText("Agregar Importe");
        inputDinero.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inputDineroFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                inputDineroFocusLost(evt);
            }
        });
        inputDinero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputDineroActionPerformed(evt);
            }
        });
        jPanel6.add(inputDinero, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 230, 40));

        jButton1.setBackground(new java.awt.Color(255, 222, 89));
        jButton1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jButton1.setText("Agregar");
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });
        jPanel6.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 230, 40));

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/euro.png"))); // NOI18N
        jLabel15.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel15.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel15.setIconTextGap(1);
        jPanel6.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 33, -1));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 440, 100));

        jPanel4.setBackground(new java.awt.Color(255, 222, 89));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/perfil.png"))); // NOI18N
        jLabel27.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel27.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel27.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel27.setIconTextGap(1);
        jPanel4.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, -1, -1));

        jLabel17.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Inicio");
        jLabel17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel17.setPreferredSize(new java.awt.Dimension(30, 20));
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 60, 23));

        jLabel18.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Favoritos");
        jLabel18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel18.setPreferredSize(new java.awt.Dimension(30, 20));
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 80, 23));

        jLabel19.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Reservas");
        jLabel19.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel19.setPreferredSize(new java.awt.Dimension(30, 20));
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 100, 23));

        jLabel20.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Perfil");
        jLabel20.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel20.setPreferredSize(new java.awt.Dimension(30, 20));
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, 90, 23));

        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/HomeUser.png"))); // NOI18N
        jLabel29.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel29.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel29.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel29.setIconTextGap(1);
        jLabel29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel29MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reservas.png"))); // NOI18N
        jLabel30.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel30.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel30.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel30.setIconTextGap(1);
        jLabel30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel30MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 40, 40));

        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/favoritos.png"))); // NOI18N
        jLabel31.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel31.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel31.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel31.setIconTextGap(1);
        jPanel4.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 40, 40));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 440, 80));

        jPanel2.setBackground(new java.awt.Color(255, 222, 89));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/arrow_left.png"))); // NOI18N
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel5.setIconTextGap(1);
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 33, -1));

        Logo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Logo_BOOK4U.png"))); // NOI18N
        Logo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Logo.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        Logo.setIconTextGap(1);
        Logo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoMouseClicked(evt);
            }
        });
        jPanel2.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, -20, -1, -1));

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/notify.png"))); // NOI18N
        jLabel14.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel14.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel14.setIconTextGap(1);
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 100));

        btn50euros.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        btn50euros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/euro.png"))); // NOI18N
        btn50euros.setText("50");
        btn50euros.setActionCommand("5");
        btn50euros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn50euros.setHideActionText(true);
        btn50euros.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btn50euros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn50eurosMouseClicked(evt);
            }
        });
        btn50euros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn50eurosActionPerformed(evt);
            }
        });
        jPanel1.add(btn50euros, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 120, 60));

        btn80euros.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        btn80euros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/euro.png"))); // NOI18N
        btn80euros.setText("80");
        btn80euros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn80euros.setHideActionText(true);
        btn80euros.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btn80euros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn80eurosMouseClicked(evt);
            }
        });
        btn80euros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn80eurosActionPerformed(evt);
            }
        });
        jPanel1.add(btn80euros, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 120, 60));

        btn40euros.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        btn40euros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/euro.png"))); // NOI18N
        btn40euros.setText("40");
        btn40euros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn40euros.setHideActionText(true);
        btn40euros.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btn40euros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn40eurosMouseClicked(evt);
            }
        });
        btn40euros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn40eurosActionPerformed(evt);
            }
        });
        jPanel1.add(btn40euros, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 120, 60));

        btn10euros.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        btn10euros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/euro.png"))); // NOI18N
        btn10euros.setText("10");
        btn10euros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn10euros.setHideActionText(true);
        btn10euros.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btn10euros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn10eurosMouseClicked(evt);
            }
        });
        btn10euros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn10eurosActionPerformed(evt);
            }
        });
        jPanel1.add(btn10euros, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 120, 60));

        btn20euros.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        btn20euros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/euro.png"))); // NOI18N
        btn20euros.setText("20");
        btn20euros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn20euros.setHideActionText(true);
        btn20euros.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btn20euros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn20eurosMouseClicked(evt);
            }
        });
        btn20euros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn20eurosActionPerformed(evt);
            }
        });
        jPanel1.add(btn20euros, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 120, 60));

        btn30euros.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        btn30euros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/euro.png"))); // NOI18N
        btn30euros.setText("30");
        btn30euros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn30euros.setHideActionText(true);
        btn30euros.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btn30euros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn30eurosMouseClicked(evt);
            }
        });
        btn30euros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn30eurosActionPerformed(evt);
            }
        });
        jPanel1.add(btn30euros, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, 120, 60));

        jPanel3.setBackground(new java.awt.Color(255, 222, 89));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel2.setText("0");
        jLabel2.setPreferredSize(new java.awt.Dimension(30, 20));
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 80, 40));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel1.setText("(10 Euros equivalen a 1 Credito)");
        jLabel1.setPreferredSize(new java.awt.Dimension(30, 20));
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 230, 30));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel3.setText("Creditos Actuales:");
        jLabel3.setPreferredSize(new java.awt.Dimension(30, 20));
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 220, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 440, 90));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputDineroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputDineroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputDineroActionPerformed

    private void inputDineroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputDineroFocusGained
        if (inputDinero.getText().equals("Agregar Importe")) {
            inputDinero.setText("");
            inputDinero.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_inputDineroFocusGained

    private void inputDineroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputDineroFocusLost

        textoDelJTextField = inputDinero.getText();

    }//GEN-LAST:event_inputDineroFocusLost

    private void btn50eurosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn50eurosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn50eurosActionPerformed

    private void btn50eurosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn50eurosMouseClicked
        saldo = 50;
        inputDinero.setText(String.valueOf(saldo));
    }//GEN-LAST:event_btn50eurosMouseClicked
                                     
    private void btn80eurosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn80eurosMouseClicked
    saldo=80;
    inputDinero.setText(String.valueOf(saldo));
    }//GEN-LAST:event_btn80eurosMouseClicked

    private void btn80eurosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn80eurosActionPerformed

    }//GEN-LAST:event_btn80eurosActionPerformed

    private void btn40eurosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn40eurosMouseClicked
        saldo = 40;
        inputDinero.setText(String.valueOf(saldo));
        // TODO add your handling code here:
    }//GEN-LAST:event_btn40eurosMouseClicked

    private void btn40eurosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn40eurosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn40eurosActionPerformed

    private void btn10eurosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn10eurosMouseClicked
        saldo = 10;
        inputDinero.setText(String.valueOf(saldo));
    }//GEN-LAST:event_btn10eurosMouseClicked

    private void btn10eurosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn10eurosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn10eurosActionPerformed

    private void btn20eurosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn20eurosMouseClicked
        saldo = 20;
        inputDinero.setText(String.valueOf(saldo));
    }//GEN-LAST:event_btn20eurosMouseClicked

    private void btn20eurosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn20eurosActionPerformed

    }//GEN-LAST:event_btn20eurosActionPerformed

    private void btn30eurosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn30eurosMouseClicked
        saldo = 30;
        inputDinero.setText(String.valueOf(saldo));
    }//GEN-LAST:event_btn30eurosMouseClicked

    private void btn30eurosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn30eurosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn30eurosActionPerformed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed

    }//GEN-LAST:event_jButton1KeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        MainPage mainPage = new MainPage(idUser);
        mainPage.setVisible(true);
        setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        String creditosA_stg = "";

        if (!inputDinero.getText().equals("Agregar Importe")) {
            try {
                int dinero = Integer.parseInt(inputDinero.getText());
                if (dinero % 10 == 0) {

                    if (dinero <= 0) {
                        JOptionPane.showMessageDialog(null, "Por favor, ingrese un múltiplo de 10 y mayor que 0.", "Error", JOptionPane.ERROR_MESSAGE);
                        return;
                    }

                    creditos_actuales = dinero + creditos_actuales;
                    creditosA_stg = String.valueOf(creditos_actuales);
                } else {
                    JOptionPane.showMessageDialog(null, "Por favor, ingrese un múltiplo de 10 y mayor que 0.", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            } catch (NumberFormatException e) {
                System.out.println("Por favor, ingrese un número válido.");
            }
        } else {
            creditos_actuales = saldo + creditos_actuales;
            creditosA_stg = String.valueOf(creditos_actuales);
        }

        jLabel2.setText(creditosA_stg);

        Conexion conexion2 = new Conexion();
        Connection connection = conexion2.DatabaseConnection();
        try {
            // Define la sentencia SQL para la actualización
            String sql = "UPDATE usuarios SET Credito = ? WHERE Id = ?";

            try (PreparedStatement preparedStatement = connection.prepareStatement(sql)) {
                preparedStatement.setInt(1, creditos_actuales);
                preparedStatement.setInt(2, idUser);

                // Ejecuta la sentencia SQL para actualizar los datos
                int rowsUpdated = preparedStatement.executeUpdate();

                if (rowsUpdated > 0) {
                    System.out.println("Actualización exitosa");
                    saldo = 0;
                    inputDinero.setText("Agregar Importe");
                } else {
                    System.out.println("No se encontró ningún usuario con el ID especificado");
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
            // Maneja la excepción apropiadamente
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void jLabel29MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel29MouseClicked
        MainPage mainPage = new MainPage(idUser);
        mainPage.setVisible(true);
        setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel29MouseClicked

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        MainPage mainPage = new MainPage(idUser);
        mainPage.setVisible(true);
        setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel17MouseClicked

    private void jLabel30MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel30MouseClicked
        // TODO add your handling code here:
        MevesReservesPage MevesReservesPage = new MevesReservesPage(idUser,creditos_actuales);
        MevesReservesPage.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jLabel30MouseClicked

    private void LogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoMouseClicked
        // TODO add your handling code here:
        MainPage mainPage = new MainPage(idUser);
        mainPage.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_LogoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreditPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreditPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreditPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreditPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreditPage().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Logo;
    private javax.swing.JButton btn10euros;
    private javax.swing.JButton btn20euros;
    private javax.swing.JButton btn30euros;
    private javax.swing.JButton btn40euros;
    private javax.swing.JButton btn50euros;
    private javax.swing.JButton btn80euros;
    private javax.swing.JTextField inputDinero;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    // End of variables declaration//GEN-END:variables
}
