/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import bd.Conexion;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.ImageIcon;
import java.awt.Image;

/**
 *
 * @author Usuario
 */
public class LoginPage extends javax.swing.JFrame {

    private Conexion conexion; // Declarar una instancia de Conexion
    public int idUserLogged = 0;

    public LoginPage() {
        initComponents();
        conexion = new Conexion(); // Inicializa la instancia de 

        this.setLocationRelativeTo(null); //Inicializa al centro de la pantalla

        ImageIcon icon = new ImageIcon(getClass().getResource("/imagenes/icono.png")); // Esto es para cambiar el icono de la app
        Image image = icon.getImage();
        setIconImage(image);
        getRootPane().setDefaultButton(loginButton);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        label1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        loginButton = new javax.swing.JButton();
        passOlvidada = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        registerButton = new javax.swing.JLabel();
        inputEmail = new javax.swing.JFormattedTextField();
        inputPass = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 222, 89));
        jPanel1.setLayout(new java.awt.FlowLayout(1, 0, -20));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Logo_BOOK4U.png"))); // NOI18N
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel5);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 100));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label1.setText("Login");
        jPanel2.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, 24));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("<html>Introduce el correo electrónico y la contraseña para iniciar sesión.</html>");
        jLabel1.setToolTipText("");
        jLabel1.setFocusable(false);
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 346, -1));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("E-mail");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("Password");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        loginButton.setBackground(new java.awt.Color(255, 222, 89));
        loginButton.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        loginButton.setText("Login");
        loginButton.setBorder(null);
        loginButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        jPanel2.add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 344, 46));

        passOlvidada.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        passOlvidada.setForeground(new java.awt.Color(0, 0, 255));
        passOlvidada.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        passOlvidada.setText("<html><u>¿Ha olvidado su contraseña?</u></html>");
        passOlvidada.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        passOlvidada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                passOlvidadaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                passOlvidadaMouseExited(evt);
            }
        });
        jPanel2.add(passOlvidada, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new java.awt.FlowLayout(1, 0, 15));

        registerButton.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        registerButton.setForeground(new java.awt.Color(0, 0, 255));
        registerButton.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        registerButton.setText("<html><u>Crear cuenta</u></html>");
        registerButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                registerButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                registerButtonMouseExited(evt);
            }
        });
        jPanel3.add(registerButton);

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 440, 60));

        inputEmail.setForeground(new java.awt.Color(153, 153, 153));
        inputEmail.setText("Indica tu correo electrónico");
        inputEmail.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        inputEmail.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        inputEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inputEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                inputEmailFocusLost(evt);
            }
        });
        inputEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputEmailActionPerformed(evt);
            }
        });
        jPanel2.add(inputEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 344, 40));

        inputPass.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        inputPass.setForeground(new java.awt.Color(153, 153, 153));
        inputPass.setText("Indica tu contraseña");
        inputPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inputPassFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                inputPassFocusLost(evt);
            }
        });
        jPanel2.add(inputPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 344, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 440, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // Obtén el correo electrónico y la contraseña ingresados por el usuario
        String email = inputEmail.getText();
        String password = inputPass.getText();

        // Realiza la verificación en la base de datos
        if (validarCredenciales(email, password)) {
            JOptionPane.showMessageDialog(this, "Inicio de sesión exitoso.");
            // Abrir el frame MainPage
            MainPage mainPage = new MainPage(idUserLogged);
            mainPage.setVisible(true);

            setVisible(false);
        } else {
            JOptionPane.showMessageDialog(this, "Credenciales incorrectas. Inténtelo de nuevo.");
        }
    }//GEN-LAST:event_loginButtonActionPerformed

    private void registerButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerButtonMouseClicked
        RegisterPage RegisterPage = new RegisterPage();
        RegisterPage.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_registerButtonMouseClicked

    private void inputEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputEmailActionPerformed

    private void passOlvidadaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passOlvidadaMouseEntered
        passOlvidada.setForeground(new Color(255, 204, 0));

    }//GEN-LAST:event_passOlvidadaMouseEntered

    private void passOlvidadaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passOlvidadaMouseExited
        passOlvidada.setForeground(new Color(0, 0, 255));
    }//GEN-LAST:event_passOlvidadaMouseExited

    private void registerButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerButtonMouseExited
        registerButton.setForeground(new Color(0, 0, 255));
    }//GEN-LAST:event_registerButtonMouseExited

    private void registerButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerButtonMouseEntered
        registerButton.setForeground(new Color(255, 204, 0));
    }//GEN-LAST:event_registerButtonMouseEntered

    private void inputEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputEmailFocusGained
        if (inputEmail.getText().equals("Indica tu correo electrónico")) {
            inputEmail.setText("");
            inputEmail.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_inputEmailFocusGained

    private void inputEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputEmailFocusLost
        if (inputEmail.getText().equals("")) {
            inputEmail.setText("Indica tu correo electrónico");
            inputEmail.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_inputEmailFocusLost

    private void inputPassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputPassFocusGained
        if (inputPass.getText().equals("Indica tu contraseña")) {
            inputPass.setText("");
            inputPass.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_inputPassFocusGained

    private void inputPassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputPassFocusLost
        if (inputPass.getText().equals("")) {
            inputPass.setText("Indica tu contraseña");
            inputPass.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_inputPassFocusLost

    // Método para validar las credenciales en la base de datos
    private boolean validarCredenciales(String email, String password) {
        Connection connection = conexion.DatabaseConnection(); // Obtén la conexión

        try {
            // Consulta SQL para verificar las credenciales
            String consulta = "SELECT * FROM usuarios WHERE Email = ? AND Password = ?";
            PreparedStatement statement = connection.prepareStatement(consulta);
            statement.setString(1, email);
            statement.setString(2, password);

            ResultSet resultado = statement.executeQuery();
            // Si se encontraron resultados, las credenciales son válidas
            if (resultado.next()) {
                idUserLogged = resultado.getInt("id");
                return true;
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return false;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField inputEmail;
    private javax.swing.JPasswordField inputPass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel label1;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel passOlvidada;
    private javax.swing.JLabel registerButton;
    // End of variables declaration//GEN-END:variables
}
