/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import bd.Conexion;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import Vistas.CreditPage;
import java.sql.SQLException;

/**
 *
 * @author alumnat
 */
public class MainPage extends javax.swing.JFrame {

    private final int idUser;
    private Conexion conexion;
    int creditos;
    /**
     * Creates new form MainPage
     */
    public MainPage(int idUser) {
        initComponents();
        System.out.println(idUser);
        this.setLocationRelativeTo(null); //Inicializa al centro de la pantalla

        ImageIcon icon = new ImageIcon(getClass().getResource("/imagenes/icono.png")); // Esto es para cambiar el icono de la app
        Image image = icon.getImage();
        setIconImage(image);
        this.idUser = idUser;

        String nombreUsuario = getNombreUsuarioPorId(idUser);
        jLabel20.setText(nombreUsuario);
        creditos = getCreditosPorId(idUser);
        jLabel20.setText(nombreUsuario);
        jLabel1.setText(String.valueOf(creditos));
    }

    private MainPage() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    // Método para validar las credenciales en la base de datos
    private String getNombreUsuarioPorId(int id) {
        Conexion conexion = new Conexion();
        Connection connection = conexion.DatabaseConnection(); // Obtén la conexión
        String nombre = "";

        try {
            // Consulta SQL para verificar las credenciales
            String consulta = "SELECT * FROM usuarios WHERE id = ?";
            PreparedStatement statement = connection.prepareStatement(consulta);
            statement.setInt(1, id);

            ResultSet resultado = statement.executeQuery();
            // Si se encontraron resultados, las credenciales son válidas
            if (resultado.next()) {
                nombre = resultado.getString("Nombre");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return nombre;
    }
    
    private int getCreditosPorId(int id) {
        Conexion conexion = new Conexion();
        Connection connection = conexion.DatabaseConnection(); // Obtén la conexión
        int creditos = 0;

        try {
            // Consulta SQL para obtener los créditos del usuario por su ID
            String consulta = "SELECT credito FROM usuarios WHERE id = ?";
            PreparedStatement statement = connection.prepareStatement(consulta);
            statement.setInt(1, id);

            ResultSet resultado = statement.executeQuery();
            // Si se encontraron resultados, obtenemos los créditos del usuario
            if (resultado.next()) {
                creditos = resultado.getInt("credito");
            }
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            // Recuerda cerrar la conexión y otros recursos relacionados con la base de datos
            try {
                connection.close();
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
        return creditos;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        imagen = new javax.swing.JLabel();
        tipoEstancia = new javax.swing.JLabel();
        direccion = new javax.swing.JLabel();
        metros = new javax.swing.JLabel();
        coste = new javax.swing.JLabel();
        inputEntrada = new javax.swing.JTextField();
        btnDateEntrada = new javax.swing.JButton();
        inputSalida = new javax.swing.JTextField();
        btnDateSalida = new javax.swing.JButton();
        reservar = new javax.swing.JButton();
        imagen1 = new javax.swing.JLabel();
        tipoEstancia1 = new javax.swing.JLabel();
        direccion1 = new javax.swing.JLabel();
        metros1 = new javax.swing.JLabel();
        inputEntrada1 = new javax.swing.JTextField();
        inputSalida1 = new javax.swing.JTextField();
        btnDateSalida1 = new javax.swing.JButton();
        btnDateEntrada1 = new javax.swing.JButton();
        reservar1 = new javax.swing.JButton();
        coste1 = new javax.swing.JLabel();
        reservar2 = new javax.swing.JButton();
        btnDateSalida2 = new javax.swing.JButton();
        inputSalida2 = new javax.swing.JTextField();
        inputEntrada2 = new javax.swing.JTextField();
        btnDateEntrada2 = new javax.swing.JButton();
        coste2 = new javax.swing.JLabel();
        metros2 = new javax.swing.JLabel();
        direccion2 = new javax.swing.JLabel();
        tipoEstancia2 = new javax.swing.JLabel();
        imagen2 = new javax.swing.JLabel();
        metros3 = new javax.swing.JLabel();
        inputSalida3 = new javax.swing.JTextField();
        coste3 = new javax.swing.JLabel();
        btnDateSalida3 = new javax.swing.JButton();
        tipoEstancia3 = new javax.swing.JLabel();
        inputEntrada3 = new javax.swing.JTextField();
        btnDateEntrada3 = new javax.swing.JButton();
        imagen3 = new javax.swing.JLabel();
        reservar3 = new javax.swing.JButton();
        direccion3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        btnReservas = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imagen.setText("jLabel2");
        jPanel3.add(imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, 20));

        tipoEstancia.setText("jLabel21");
        jPanel3.add(tipoEstancia, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        direccion.setText("jLabel2");
        jPanel3.add(direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        metros.setText("jLabel2");
        jPanel3.add(metros, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        coste.setText("jLabel2");
        jPanel3.add(coste, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, -1, -1));

        inputEntrada.setText("jTextField3");
        jPanel3.add(inputEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        btnDateEntrada.setText("jButton2");
        jPanel3.add(btnDateEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 20, -1));

        inputSalida.setText("jTextField3");
        jPanel3.add(inputSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        btnDateSalida.setText("jButton2");
        jPanel3.add(btnDateSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 20, -1));

        reservar.setText("jButton2");
        jPanel3.add(reservar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, -1, -1));

        imagen1.setText("jLabel2");
        jPanel3.add(imagen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, -1, 20));

        tipoEstancia1.setText("jLabel21");
        jPanel3.add(tipoEstancia1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        direccion1.setText("jLabel2");
        jPanel3.add(direccion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        metros1.setText("jLabel2");
        jPanel3.add(metros1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        inputEntrada1.setText("jTextField3");
        jPanel3.add(inputEntrada1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, -1, -1));

        inputSalida1.setText("jTextField3");
        jPanel3.add(inputSalida1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, -1, -1));

        btnDateSalida1.setText("jButton2");
        jPanel3.add(btnDateSalida1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 420, 20, -1));

        btnDateEntrada1.setText("jButton2");
        jPanel3.add(btnDateEntrada1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, 20, -1));

        reservar1.setText("jButton2");
        jPanel3.add(reservar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 420, -1, -1));

        coste1.setText("jLabel2");
        jPanel3.add(coste1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, -1, -1));

        reservar2.setText("jButton2");
        jPanel3.add(reservar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 640, -1, -1));

        btnDateSalida2.setText("jButton2");
        jPanel3.add(btnDateSalida2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 640, 20, -1));

        inputSalida2.setText("jTextField3");
        jPanel3.add(inputSalida2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 640, -1, -1));

        inputEntrada2.setText("jTextField3");
        jPanel3.add(inputEntrada2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 610, -1, -1));

        btnDateEntrada2.setText("jButton2");
        jPanel3.add(btnDateEntrada2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 610, 20, -1));

        coste2.setText("jLabel2");
        jPanel3.add(coste2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 580, -1, -1));

        metros2.setText("jLabel2");
        jPanel3.add(metros2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 580, -1, -1));

        direccion2.setText("jLabel2");
        jPanel3.add(direccion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, -1, -1));

        tipoEstancia2.setText("jLabel21");
        jPanel3.add(tipoEstancia2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, -1, -1));

        imagen2.setText("jLabel2");
        jPanel3.add(imagen2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 470, -1, 20));

        metros3.setText("jLabel2");
        jPanel3.add(metros3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 790, -1, -1));

        inputSalida3.setText("jTextField3");
        jPanel3.add(inputSalida3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 850, -1, -1));

        coste3.setText("jLabel2");
        jPanel3.add(coste3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 790, -1, -1));

        btnDateSalida3.setText("jButton2");
        jPanel3.add(btnDateSalida3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 850, 20, -1));

        tipoEstancia3.setText("jLabel21");
        jPanel3.add(tipoEstancia3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 730, -1, -1));

        inputEntrada3.setText("jTextField3");
        jPanel3.add(inputEntrada3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 820, -1, -1));

        btnDateEntrada3.setText("jButton2");
        jPanel3.add(btnDateEntrada3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 820, 20, -1));

        imagen3.setText("jLabel2");
        jPanel3.add(imagen3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 680, -1, 20));

        reservar3.setText("jButton2");
        jPanel3.add(reservar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 850, -1, -1));

        direccion3.setText("jLabel2");
        jPanel3.add(direccion3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 760, -1, -1));

        jScrollPane1.setViewportView(jPanel3);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 280, 930));

        jPanel4.setBackground(new java.awt.Color(255, 222, 89));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/perfil.png"))); // NOI18N
        jLabel27.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel27.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel27.setIconTextGap(1);
        jPanel4.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, -1, -1));

        jLabel17.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel17.setText("Buscar");
        jLabel17.setPreferredSize(new java.awt.Dimension(30, 20));
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 50, 23));

        jLabel18.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Favoritos");
        jLabel18.setPreferredSize(new java.awt.Dimension(30, 20));
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 80, 23));

        jLabel19.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Reservas");
        jLabel19.setPreferredSize(new java.awt.Dimension(30, 20));
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 100, 23));

        jLabel20.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Perfil");
        jLabel20.setPreferredSize(new java.awt.Dimension(30, 20));
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, 90, 23));

        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/busqueda.png"))); // NOI18N
        jLabel29.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel29.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel29.setIconTextGap(1);
        jPanel4.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        btnReservas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnReservas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reservas.png"))); // NOI18N
        btnReservas.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnReservas.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnReservas.setIconTextGap(1);
        btnReservas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReservasMouseClicked(evt);
            }
        });
        jPanel4.add(btnReservas, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 40, 40));

        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/favoritos.png"))); // NOI18N
        jLabel31.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel31.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel31.setIconTextGap(1);
        jPanel4.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 40, 40));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 440, 80));

        jPanel2.setBackground(new java.awt.Color(255, 222, 89));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/coin1.png"))); // NOI18N
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel5.setIconTextGap(1);
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 20, 33, -1));

        jLabel1.setText("0");
        jLabel1.setPreferredSize(new java.awt.Dimension(30, 20));
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 20, 36, 30));

        jPanel5.setBackground(new java.awt.Color(255, 222, 89));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/casas_rurales.png"))); // NOI18N
        jLabel8.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel8.setIconTextGap(1);
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        jLabel3.setText("Casas rurales");
        jLabel3.setPreferredSize(new java.awt.Dimension(30, 20));
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 80, 30));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/apartamentos.png"))); // NOI18N
        jLabel9.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel9.setIconTextGap(1);
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, -1, -1));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        jLabel4.setText("Apartamentos");
        jLabel4.setPreferredSize(new java.awt.Dimension(30, 20));
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 90, 30));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Hoteles");
        jLabel7.setPreferredSize(new java.awt.Dimension(30, 20));
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 50, 30));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Hoteles.png"))); // NOI18N
        jLabel10.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel10.setIconTextGap(1);
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, -1, -1));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/apartahoteles.png"))); // NOI18N
        jLabel11.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel11.setIconTextGap(1);
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, -1, -1));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("Apartahoteles");
        jLabel12.setPreferredSize(new java.awt.Dimension(30, 20));
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 100, 30));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 62, 450, -1));

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Logo_BOOK4U_Little.png"))); // NOI18N
        jLabel13.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel13.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel13.setIconTextGap(1);
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, -1));

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/notify.png"))); // NOI18N
        jLabel14.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel14.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel14.setIconTextGap(1);
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 100));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 1050));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReservasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReservasMouseClicked
        MevesReservesPage MevesReservesPage = new MevesReservesPage(idUser);

        MevesReservesPage.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnReservasMouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        CreditPage creditPage = new CreditPage(idUser);
        creditPage.setVisible(true);
        this.dispose();      // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDateEntrada;
    private javax.swing.JButton btnDateEntrada1;
    private javax.swing.JButton btnDateEntrada2;
    private javax.swing.JButton btnDateEntrada3;
    private javax.swing.JButton btnDateSalida;
    private javax.swing.JButton btnDateSalida1;
    private javax.swing.JButton btnDateSalida2;
    private javax.swing.JButton btnDateSalida3;
    private javax.swing.JLabel btnReservas;
    private javax.swing.JLabel coste;
    private javax.swing.JLabel coste1;
    private javax.swing.JLabel coste2;
    private javax.swing.JLabel coste3;
    private javax.swing.JLabel direccion;
    private javax.swing.JLabel direccion1;
    private javax.swing.JLabel direccion2;
    private javax.swing.JLabel direccion3;
    private javax.swing.JLabel imagen;
    private javax.swing.JLabel imagen1;
    private javax.swing.JLabel imagen2;
    private javax.swing.JLabel imagen3;
    private javax.swing.JTextField inputEntrada;
    private javax.swing.JTextField inputEntrada1;
    private javax.swing.JTextField inputEntrada2;
    private javax.swing.JTextField inputEntrada3;
    private javax.swing.JTextField inputSalida;
    private javax.swing.JTextField inputSalida1;
    private javax.swing.JTextField inputSalida2;
    private javax.swing.JTextField inputSalida3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel metros;
    private javax.swing.JLabel metros1;
    private javax.swing.JLabel metros2;
    private javax.swing.JLabel metros3;
    private javax.swing.JButton reservar;
    private javax.swing.JButton reservar1;
    private javax.swing.JButton reservar2;
    private javax.swing.JButton reservar3;
    private javax.swing.JLabel tipoEstancia;
    private javax.swing.JLabel tipoEstancia1;
    private javax.swing.JLabel tipoEstancia2;
    private javax.swing.JLabel tipoEstancia3;
    // End of variables declaration//GEN-END:variables
}
