/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import bd.Conexion;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Date;
import javax.swing.JOptionPane;
import java.sql.Timestamp;

/**
 *
 * @author Usuario
 */
public class RegisterPage extends javax.swing.JFrame {

    private Conexion conexion;
    
    public RegisterPage() {
        initComponents();
        conexion = new Conexion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        label1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        registerButton = new javax.swing.JButton();
        inputEmail = new javax.swing.JFormattedTextField();
        inputNombre = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        inputPass = new javax.swing.JFormattedTextField();
        inputApellido1 = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        inputApellido2 = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        inputDNI = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        inputDomicilio = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        volverLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro");
        setMinimumSize(new java.awt.Dimension(440, 570));
        setPreferredSize(new java.awt.Dimension(440, 570));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 222, 89));
        jPanel1.setMinimumSize(new java.awt.Dimension(145, 105));
        jPanel1.setPreferredSize(new java.awt.Dimension(145, 105));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, -20));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Logo_BOOK4U.png"))); // NOI18N
        jLabel9.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel9);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 100));

        label1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label1.setText("Registro");
        getContentPane().add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, 24));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Rellena los campos para crear un usuario");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 97, 346, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("E-mail");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 134, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Nombre");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 294, -1, -1));

        registerButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        registerButton.setText("Registrarse");
        registerButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });
        getContentPane().add(registerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 713, 344, 46));

        inputEmail.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        inputEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputEmailActionPerformed(evt);
            }
        });
        getContentPane().add(inputEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 165, 361, 40));
        getContentPane().add(inputNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 325, 361, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Password");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 211, -1, -1));
        getContentPane().add(inputPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 248, 361, 40));
        getContentPane().add(inputApellido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 402, 361, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Apellido 1");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 371, -1, -1));
        getContentPane().add(inputApellido2, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 479, 361, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Apellido 2");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 448, -1, -1));
        getContentPane().add(inputDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 556, 344, 40));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("DNI");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 525, -1, -1));
        getContentPane().add(inputDomicilio, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 630, 344, 40));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Domicilio");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 602, -1, -1));

        volverLogin.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        volverLogin.setText("Login");
        volverLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                volverLoginMouseClicked(evt);
            }
        });
        getContentPane().add(volverLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 676, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        String email = inputEmail.getText();
        String password = inputPass.getText();
        String nombre = inputNombre.getText();
        String apellido1 = inputApellido1.getText();
        String apellido2 = inputApellido2.getText();
        String dni = inputDNI.getText();
        String domicilio = inputDomicilio.getText();

        // Verifica que no haya campos nulos
        if (email.isEmpty() || password.isEmpty() || nombre.isEmpty() || apellido1.isEmpty() || dni.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos.");
            return;
        }

        // Verifica si el email ya existe en la base de datos
        if (emailExists(email)) {
            JOptionPane.showMessageDialog(this, "El email ya está registrado.");
        } else {
            // Inserta el nuevo usuario en la base de datos
            if (insertUser(email, password, nombre, apellido1, apellido2, dni, domicilio)) {
                JOptionPane.showMessageDialog(this, "Registro exitoso.");
            } else {
                JOptionPane.showMessageDialog(this, "Ocurrió un error al registrar el usuario.");
            }
        }
    }//GEN-LAST:event_registerButtonActionPerformed

    private boolean emailExists(String email) {
        Connection connection = conexion.DatabaseConnection();
        try {
            String consulta = "SELECT Email FROM usuarios WHERE Email = ?";
            PreparedStatement statement = connection.prepareStatement(consulta);
            statement.setString(1, email);
            ResultSet resultado = statement.executeQuery();
            return resultado.next();
        } catch (Exception e) {
            e.printStackTrace();
            return false;
        }
    }

    private boolean insertUser(String email, String password, String nombre, String apellido1, String apellido2, String dni, String domicilio) {
        Connection connection = conexion.DatabaseConnection();
        try {
            String consulta = "INSERT INTO usuarios (Email, Password, Nombre, Apellido1, Apellido2, DNI, Domicilio, Fecha_alta) VALUES (?, ?, ?, ?, ?, ?, ?, ?)";
            PreparedStatement statement = connection.prepareStatement(consulta);
            statement.setString(1, email);
            statement.setString(2, password);
            statement.setString(3, nombre);
            statement.setString(4, apellido1);
            statement.setString(5, apellido2);
            statement.setString(6, dni);
            statement.setString(7, domicilio);

            // Obten la fecha actual
            Date fechaActual = new Date();
            Timestamp fechaAlta = new Timestamp(fechaActual.getTime());
            statement.setTimestamp(8, fechaAlta); 
            
            return statement.executeUpdate() > 0;
        } catch (Exception e) {
            e.printStackTrace();
            return false;
        }
    }
    
    private void volverLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverLoginMouseClicked
        LoginPage LoginPage = new LoginPage();
        LoginPage.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_volverLoginMouseClicked

    private void inputEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputEmailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField inputApellido1;
    private javax.swing.JFormattedTextField inputApellido2;
    private javax.swing.JFormattedTextField inputDNI;
    private javax.swing.JFormattedTextField inputDomicilio;
    private javax.swing.JFormattedTextField inputEmail;
    private javax.swing.JFormattedTextField inputNombre;
    private javax.swing.JFormattedTextField inputPass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label1;
    private javax.swing.JButton registerButton;
    private javax.swing.JLabel volverLogin;
    // End of variables declaration//GEN-END:variables
}
